### ISSUE TITLE
2번째시간 트위터 로그인 완료!

### ISSUE THREAD

**Issue by techvit7** [moonbird-thinker/wordpress_twitter_auto_backlink#1]
2번째시간 트위터 로그인 완료!
오늘 너무 수고했네요!!!!!
![2023-11-24 21 27 48](https://github.com/moonbird-thinker/wordpress_twitter_auto_backlink/assets/148855324/b9109850-ec72-4ecc-a92d-766301da5519)

**Comment by moonbird-thinker** [comment]
화이팅입니다.^^
